import React from "react";
import { Type, Heading1, Heading2, Heading3, Heading4, List, ListOrdered, CheckSquare, ChevronDown, Image as ImageIcon, Video, Music, FileText, Table, BarChart2, Quote, Minus, Lightbulb, Columns, LayoutTemplate, Code, Bookmark, Sigma, HelpCircle, AtSign, Calendar, Smile, Link as LinkIcon } from "lucide-react";

export type SlashCommand = {
  id: string;
  label: string;
  description: string;
  search: string;
  kind: "inline" | "block";
  category?: string;
  insertText?: string;
  blockKind?: string;
  shortcut?: string;
  icon?: React.ReactNode;
  preview?: React.ReactNode;
};

export const getSlashCommands = (t: (key: string) => string): SlashCommand[] => [
  { id: "text", category: "basic", label: t("slashCommands.textLabel") || "Texto", description: t("slashCommands.textDesc") || "Comienza a escribir con texto normal.", search: t("slashCommands.textSearch"), kind: "inline", insertText: "", shortcut: "", icon: <Type className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><span className="text-foreground">{t("slashPreviews.text")}</span></div> },
  { id: "heading-1", category: "basic", label: t("slashCommands.h1Label") || "Encabezado 1", description: t("slashCommands.h1Desc") || "Encabezado de sección grande.", search: t("slashCommands.h1Search"), kind: "inline", insertText: "# ", shortcut: "#", icon: <Heading1 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h1 className="text-2xl font-bold">{t("slashPreviews.h1")}</h1></div> },
  { id: "heading-2", category: "basic", label: t("slashCommands.h2Label") || "Encabezado 2", description: t("slashCommands.h2Desc") || "Encabezado de sección mediano.", search: t("slashCommands.h2Search"), kind: "inline", insertText: "## ", shortcut: "##", icon: <Heading2 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h2 className="text-xl font-semibold">{t("slashPreviews.h2")}</h2></div> },
  { id: "heading-3", category: "basic", label: t("slashCommands.h3Label") || "Encabezado 3", description: t("slashCommands.h3Desc") || "Encabezado de sección pequeño.", search: t("slashCommands.h3Search"), kind: "inline", insertText: "### ", shortcut: "###", icon: <Heading3 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h3 className="text-lg font-medium">{t("slashPreviews.h3")}</h3></div> },
  { id: "heading-4", category: "basic", label: t("slashCommands.h4Label") || "Encabezado 4", description: t("slashCommands.h4Desc") || "Encabezado de sección extra pequeño.", search: t("slashCommands.h4Search"), kind: "inline", insertText: "#### ", shortcut: "####", icon: <Heading4 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h4 className="text-base font-medium">{t("slashPreviews.h4")}</h4></div> },
  { id: "bulleted-list", category: "basic", label: t("slashCommands.bulletLabel") || "Lista de viñetas", description: t("slashCommands.bulletDesc") || "Crea una lista con viñetas simple.", search: t("slashCommands.bulletSearch"), kind: "inline", insertText: "- ", shortcut: "-", icon: <List className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><ul className="list-disc pl-4"><li>{t("slashPreviews.bullet1")}</li><li>{t("slashPreviews.bullet2")}</li><li>{t("slashPreviews.bullet3")}</li></ul></div> },
  { id: "numbered-list", category: "basic", label: t("slashCommands.numLabel") || "Lista numerada", description: t("slashCommands.numDesc") || "Crea una lista con numeración.", search: t("slashCommands.numSearch"), kind: "inline", insertText: "1. ", shortcut: "1.", icon: <ListOrdered className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><ol className="list-decimal pl-4"><li>{t("slashPreviews.num1")}</li><li>{t("slashPreviews.num2")}</li><li>{t("slashPreviews.num3")}</li></ol></div> },
  { id: "checklist", category: "basic", label: t("slashCommands.checkLabel") || "Lista de tareas", description: t("slashCommands.checkDesc") || "Seguimiento de tareas con casillas.", search: t("slashCommands.checkSearch"), kind: "block", blockKind: "checklist", shortcut: "[]", icon: <CheckSquare className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex flex-col gap-2"><div className="flex items-center gap-2"><div className="w-4 h-4 border border-primary rounded-sm bg-primary text-primary-foreground flex items-center justify-center"><CheckSquare className="w-3 h-3" /></div> <span className="line-through text-muted-foreground">{t("slashPreviews.checkCompleted")}</span></div><div className="flex items-center gap-2"><div className="w-4 h-4 border border-border rounded-sm"></div> <span>{t("slashPreviews.checkPending")}</span></div></div> },
  { id: "accordion", category: "basic", label: t("slashCommands.accLabel") || "Alternar (Toggle)", description: t("slashCommands.accDesc") || "Bloque de contenido desplegable.", search: t("slashCommands.accSearch"), kind: "block", blockKind: "accordion", icon: <ChevronDown className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="flex items-center gap-2 font-medium"><ChevronDown className="w-4 h-4" /> <span>{t("slashPreviews.accClick")}</span></div><div className="pl-6 pt-1 text-muted-foreground text-sm">{t("slashPreviews.accContent")}</div></div>  },
  { id: "image", category: "media", label: "Imagen", description: "Sube o incrusta una imagen.", search: "imagen photo picture media", kind: "block", blockKind: "image", icon: <ImageIcon className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-center gap-4"><ImageIcon className="w-10 h-10 text-muted-foreground/50" /></div> },
  { id: "video", category: "media", label: "Vídeo", description: "Añade un vídeo web o sube uno.", search: "video mp4 media", kind: "block", blockKind: "video", icon: <Video className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-center gap-4"><Video className="w-10 h-10 text-muted-foreground/50" /></div> },
  { id: "audio", category: "media", label: "Audio", description: "Añade un archivo de audio.", search: "audio mp3 media", kind: "block", blockKind: "audio", icon: <Music className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-center gap-4"><Music className="w-10 h-10 text-muted-foreground/50" /></div> },
  { id: "code", category: "media", label: "Código", description: "Captura fragmentos de código.", search: "code codigo block snippet", kind: "block", blockKind: "code", icon: <Code className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md font-mono text-sm text-muted-foreground">```<br/>const test = 1;<br/>```</div> },
  { id: "file", category: "media", label: "Archivo", description: "Sube un archivo genérico.", search: "archivo file adjunto", kind: "block", blockKind: "file", icon: <FileText className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-center gap-4"><FileText className="w-10 h-10 text-muted-foreground/50" /></div> },
  { id: "bookmark", category: "media", label: "Miniatura web", description: "Añade un marcador visual de una web.", search: "link miniatura web enlace bookmark", kind: "block", blockKind: "bookmark", icon: <Bookmark className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="h-2 bg-muted/50 mb-2 w-3/4 rounded-sm"></div><div className="h-2 bg-muted/50 w-1/2 rounded-sm"></div></div> },
  { id: "math", category: "advanced", label: "Ecuación de bloque", description: "Muestra una ecuación matemática independiente.", search: "math formula ecuacion block", kind: "block", blockKind: "math", icon: <Sigma className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md text-center text-muted-foreground">$$ \int_0^T f(t) dt $$</div> },
  { id: "table", category: "advanced", label: t("slashCommands.tabLabel") || "Tabla", description: t("slashCommands.tabDesc") || "Añade contenido tabular estático.", search: t("slashCommands.tabSearch"), kind: "block", blockKind: "table", icon: <Table className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><table className="w-full text-xs text-left border-collapse"><thead><tr className="border-b border-border"><th className="pb-1">{t("slashPreviews.tabCol1")}</th><th className="pb-1">{t("slashPreviews.tabCol2")}</th></tr></thead><tbody><tr className="border-b border-border/50"><td className="py-1">{t("slashPreviews.tabDataA")}</td><td className="py-1">{t("slashPreviews.tabDataB")}</td></tr><tr><td className="py-1">{t("slashPreviews.tabDataC")}</td><td className="py-1">{t("slashPreviews.tabDataD")}</td></tr></tbody></table></div> },
  { id: "graph", category: "advanced", label: t("slashCommands.graphLabel") || "Gráfico", description: t("slashCommands.graphDesc") || "Añade un gráfico básico.", search: t("slashCommands.graphSearch"), kind: "block", blockKind: "graph", icon: <BarChart2 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-end gap-2 h-20"><div className="w-4 bg-primary/40 h-8 rounded-t-sm"></div><div className="w-4 bg-primary/60 h-16 rounded-t-sm"></div><div className="w-4 bg-primary/80 h-12 rounded-t-sm"></div><div className="w-4 bg-primary h-full rounded-t-sm"></div></div> },
  { id: "quote", category: "basic", label: t("slashCommands.quoteLabel") || "Cita", description: t("slashCommands.quoteDesc") || "Captura una cita.", search: t("slashCommands.quoteSearch"), kind: "block", blockKind: "quote", shortcut: ">", icon: <Quote className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="pl-3 border-l-2 border-primary text-muted-foreground italic">{t("slashPreviews.quoteText")}</div></div> },
  { id: "divider", category: "basic", label: t("slashCommands.divLabel") || "Divisor", description: t("slashCommands.divDesc") || "Separa visualmente los bloques.", search: t("slashCommands.divSearch"), kind: "block", blockKind: "divider", shortcut: "---", icon: <Minus className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex items-center h-16"><div className="w-full h-[1px] bg-border"></div></div> },
  { id: "callout", category: "advanced", label: t("slashCommands.callLabel") || "Callout", description: t("slashCommands.callDesc") || "Hace que el texto destaque.", search: t("slashCommands.callSearch"), kind: "block", blockKind: "callout", icon: <Lightbulb className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-md flex gap-3 text-foreground"><Lightbulb className="w-5 h-5 text-amber-500" /><span>{t("slashPreviews.calloutText")}</span></div> },
  { id: "tabs", category: "advanced", label: t("slashCommands.tabsLabel"), description: t("slashCommands.tabsDesc"), search: t("slashCommands.tabsSearch"), kind: "block", blockKind: "tabs", icon: <LayoutTemplate className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="flex gap-4 border-b border-border mb-2"><div className="font-semibold border-b-2 border-primary pb-1">{t("slashPreviews.tab1")}</div><div className="text-muted-foreground pb-1">{t("slashPreviews.tab2")}</div></div><div className="text-sm text-muted-foreground">{t("slashPreviews.tabContent1")}</div></div> },
    { id: "columns", category: "advanced", label: t("slashCommands.colsLabel"), description: t("slashCommands.colsDesc"), search: t("slashCommands.colsSearch"), kind: "block", blockKind: "columns", icon: <Columns className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex gap-4"><div className="flex-1 bg-background border border-border/50 h-16 rounded"></div><div className="flex-1 bg-background border border-border/50 h-16 rounded"></div></div> },

    // Elementos integrados
    { id: "mention-person", category: "inline", label: "Mencionar a una persona", description: "Menciona a un miembro del equipo.", search: "mencionar user persona", kind: "inline", insertText: "@", icon: <AtSign className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><span className="bg-primary/20 text-primary px-1 rounded">@Persona</span></div> },
    { id: "mention-page", category: "inline", label: "Mencionar una página o una fuente de datos", description: "Enlaza otro documento o tablero.", search: "mencionar link page documento", kind: "inline", insertText: "+", icon: <LinkIcon className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><span className="bg-accent/20 text-accent px-1 rounded">📄 Documento</span></div> }
];
