import React from "react";
import { Type, Heading1, Heading2, Heading3, Heading4, List, ListOrdered, CheckSquare, ChevronDown, Image as ImageIcon, Table, BarChart2, Quote, Minus, Lightbulb } from "lucide-react";

export type SlashCommand = {
  id: string;
  label: string;
  description: string;
  search: string;
  kind: "inline" | "block";
  insertText?: string;
  blockKind?: string;
  shortcut?: string;
  icon?: React.ReactNode;
  preview?: React.ReactNode;
};

export const getSlashCommands = (t: (key: string) => string): SlashCommand[] => [
  { id: "text", label: t("slashCommands.textLabel") || "Texto", description: t("slashCommands.textDesc") || "Comienza a escribir con texto normal.", search: t("slashCommands.textSearch"), kind: "inline", insertText: "", shortcut: "", icon: <Type className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><span className="text-foreground">Texto simple</span></div> },
  { id: "heading-1", label: t("slashCommands.h1Label") || "Encabezado 1", description: t("slashCommands.h1Desc") || "Encabezado de sección grande.", search: t("slashCommands.h1Search"), kind: "inline", insertText: "# ", shortcut: "#", icon: <Heading1 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h1 className="text-2xl font-bold">Encabezado 1</h1></div> },
  { id: "heading-2", label: t("slashCommands.h2Label") || "Encabezado 2", description: t("slashCommands.h2Desc") || "Encabezado de sección mediano.", search: t("slashCommands.h2Search"), kind: "inline", insertText: "## ", shortcut: "##", icon: <Heading2 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h2 className="text-xl font-semibold">Encabezado 2</h2></div> },
  { id: "heading-3", label: t("slashCommands.h3Label") || "Encabezado 3", description: t("slashCommands.h3Desc") || "Encabezado de sección pequeño.", search: t("slashCommands.h3Search"), kind: "inline", insertText: "### ", shortcut: "###", icon: <Heading3 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h3 className="text-lg font-medium">Encabezado 3</h3></div> },
  { id: "heading-4", label: t("slashCommands.h4Label") || "Encabezado 4", description: t("slashCommands.h4Desc") || "Encabezado de sección extra pequeño.", search: t("slashCommands.h4Search"), kind: "inline", insertText: "#### ", shortcut: "####", icon: <Heading4 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><h4 className="text-base font-medium">Encabezado 4</h4></div> },
  { id: "bulleted-list", label: t("slashCommands.bulletLabel") || "Lista de viñetas", description: t("slashCommands.bulletDesc") || "Crea una lista con viñetas simple.", search: t("slashCommands.bulletSearch"), kind: "inline", insertText: "- ", shortcut: "-", icon: <List className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><ul className="list-disc pl-4"><li>Elemento 1</li><li>Elemento 2</li><li>Elemento 3</li></ul></div> },
  { id: "numbered-list", label: t("slashCommands.numLabel") || "Lista numerada", description: t("slashCommands.numDesc") || "Crea una lista con numeración.", search: t("slashCommands.numSearch"), kind: "inline", insertText: "1. ", shortcut: "1.", icon: <ListOrdered className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><ol className="list-decimal pl-4"><li>Paso 1</li><li>Paso 2</li><li>Paso 3</li></ol></div> },
  { id: "checklist", label: t("slashCommands.checkLabel") || "Lista de tareas", description: t("slashCommands.checkDesc") || "Seguimiento de tareas con casillas.", search: t("slashCommands.checkSearch"), kind: "block", blockKind: "checklist", shortcut: "[]", icon: <CheckSquare className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex flex-col gap-2"><div className="flex items-center gap-2"><div className="w-4 h-4 border border-primary rounded-sm bg-primary text-primary-foreground flex items-center justify-center"><CheckSquare className="w-3 h-3" /></div> <span className="line-through text-muted-foreground">Completado</span></div><div className="flex items-center gap-2"><div className="w-4 h-4 border border-border rounded-sm"></div> <span>Pendiente</span></div></div> },
  { id: "accordion", label: t("slashCommands.accLabel") || "Alternar (Toggle)", description: t("slashCommands.accDesc") || "Bloque de contenido desplegable.", search: t("slashCommands.accSearch"), kind: "block", blockKind: "accordion", icon: <ChevronDown className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="flex items-center gap-2 font-medium"><ChevronDown className="w-4 h-4" /> <span>Hacer clic para expandir</span></div><div className="pl-6 pt-1 text-muted-foreground text-sm">Contenido oculto aquí...</div></div>  },
  { id: "image", label: t("slashCommands.imgLabel") || "Imagen", description: t("slashCommands.imgDesc") || "Sube o incrusta una imagen.", search: t("slashCommands.imgSrc"), kind: "block", blockKind: "image", icon: <ImageIcon className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center"><ImageIcon className="w-16 h-16 text-muted-foreground/30" /></div> },
  { id: "table", label: t("slashCommands.tabLabel") || "Tabla", description: t("slashCommands.tabDesc") || "Añade contenido tabular estático.", search: t("slashCommands.tabSearch"), kind: "block", blockKind: "table", icon: <Table className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><table className="w-full text-xs text-left border-collapse"><thead><tr className="border-b border-border"><th className="pb-1">Col 1</th><th className="pb-1">Col 2</th></tr></thead><tbody><tr className="border-b border-border/50"><td className="py-1">Dato A</td><td className="py-1">Dato B</td></tr><tr><td className="py-1">Dato C</td><td className="py-1">Dato D</td></tr></tbody></table></div> },
  { id: "graph", label: t("slashCommands.graphLabel") || "Gráfico", description: t("slashCommands.graphDesc") || "Añade un gráfico básico.", search: t("slashCommands.graphSearch"), kind: "block", blockKind: "graph", icon: <BarChart2 className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex justify-center items-end gap-2 h-20"><div className="w-4 bg-primary/40 h-8 rounded-t-sm"></div><div className="w-4 bg-primary/60 h-16 rounded-t-sm"></div><div className="w-4 bg-primary/80 h-12 rounded-t-sm"></div><div className="w-4 bg-primary h-full rounded-t-sm"></div></div> },
  { id: "quote", label: t("slashCommands.quoteLabel") || "Cita", description: t("slashCommands.quoteDesc") || "Captura una cita.", search: t("slashCommands.quoteSearch"), kind: "block", blockKind: "quote", shortcut: ">", icon: <Quote className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md"><div className="pl-3 border-l-2 border-primary text-muted-foreground italic">"Simplicity is the ultimate sophistication."</div></div> },
  { id: "divider", label: t("slashCommands.divLabel") || "Divisor", description: t("slashCommands.divDesc") || "Separa visualmente los bloques.", search: t("slashCommands.divSearch"), kind: "block", blockKind: "divider", shortcut: "---", icon: <Minus className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-muted/20 border border-border rounded-md flex items-center h-16"><div className="w-full h-[1px] bg-border"></div></div> },
  { id: "callout", label: t("slashCommands.callLabel") || "Callout", description: t("slashCommands.callDesc") || "Hace que el texto destaque.", search: t("slashCommands.callSearch"), kind: "block", blockKind: "callout", icon: <Lightbulb className="w-5 h-5 text-muted-foreground" />, preview: <div className="p-4 bg-accent/20 border border-accent/20 rounded-md flex gap-3 text-accent-foreground"><Lightbulb className="w-5 h-5 text-amber-500" /><span>Información importante o idea destacada aquí.</span></div> }
];
