"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ChevronLeft, ChevronRight, Loader2, Plus, Send, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/lib/toast";
import { useTranslations } from "@/components/providers/i18n-provider";
import { useParams } from "next/navigation";
import { useSession } from "@/components/providers/session-provider";
import { listScripts, type ScriptSummary } from "@/lib/api/scripts";
import { resolveNestedBricks } from "@/lib/bricks/nesting";
import { UnifiedBrickList } from "./unified-brick-list";
import {
  createDefaultFormFieldConfig,
  FormFieldRuntimeProvider,
  type FormFieldType,
  normalizeFormFieldConfig,
} from "./unified-form-field-brick.web";
import { WorkspaceMemberLike } from "@/lib/workspace-members";
import { TableBrickPicker, type TableBrickPickerSelection } from "./table-brick-picker";
import { generateFormFieldsFromColumns, generateCardFormFields } from "@/lib/form-brick-table-mapper";
import { listTeamBoards } from "@/lib/api/contracts";
type FormPage = {
  id: string;
  label: string;
};

type FormBrickContent = {
  title?: string;
  description?: string;
  submitLabel?: string;
  webhookUrl?: string;
  scriptId?: string;
  successMessage?: string;
  pages?: FormPage[];
  childrenByContainer?: Record<string, string[]>;
  fields?: any[]; // Deprecated, use field bricks instead
  // Database connector
  tableConnectorId?: string;
  tableConnectorSource?: "local" | "document" | "mesh" | "board";
  tableConnectorLabel?: string;
  tableConnectorDocId?: string;
  autoGeneratedFields?: boolean;
};

interface UnifiedFormBrickProps {
  id: string;
  content: FormBrickContent;
  canEdit: boolean;
  onUpdate: (content: FormBrickContent) => void;
  activeBricks?: any[];
  onAddBrick?: (kind: string, afterBrickId?: string, parentProps?: { parentId: string; containerId: string }, initialContent?: any) => void;
  onDeleteBrick?: (id: string) => void;
  onUpdateBrick?: (id: string, content: any) => void;
  onReorderBricks?: (ids: string[]) => void;
  onCrossContainerDrop?: (
    activeId: string,
    overId: string,
    options?: { intent?: "move" | "merge-text"; sourceContainerToken?: string; targetContainerToken?: string },
  ) => void;
  documents?: any[];
  boards?: any[];
  users?: WorkspaceMemberLike[];
}

const DEFAULT_PAGE_ID = "page-1";
const DEFAULT_PAGE_LABEL = "Paso 1";

const createPage = (index: number): FormPage => ({
  id: `page-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  label: `Paso ${index}`,
});

const isRequiredFieldMissing = (type: FormFieldType, required: boolean | undefined, value: string | boolean | undefined) => {
  if (!required) return false;
  if (type === "checkbox") return value !== true;
  return typeof value !== "string" || value.trim().length === 0;
};

const normalizeConditionText = (value: string | boolean | undefined): string => {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "string") return value.trim().toLowerCase();
  return "";
};

const evaluateFieldCondition = (
  condition: {
    enabled?: boolean;
    sourceFieldId?: string;
    operator?: string;
    value?: string;
  } | undefined,
  sourceValue: string | boolean | undefined,
): boolean => {
  if (!condition?.enabled) return true;
  const sourceFieldId = String(condition.sourceFieldId || "").trim();
  if (sourceFieldId.length === 0) return true;

  const operator = String(condition.operator || "equals");
  const current = normalizeConditionText(sourceValue);
  const expected = normalizeConditionText(condition.value || "");

  if (operator === "equals") return current === expected;
  if (operator === "not_equals") return current !== expected;
  if (operator === "contains") return current.includes(expected);
  if (operator === "not_contains") return !current.includes(expected);
  if (operator === "is_empty") return current.length === 0;
  if (operator === "is_not_empty") return current.length > 0;
  if (operator === "is_true") return current === "true" || current === "1" || current === "si" || current === "yes";
  if (operator === "is_false") return current === "false" || current === "0" || current === "no";

  return true;
};

export function UnifiedFormBrick({
  id,
  content,
  canEdit,
  onUpdate,
  activeBricks = [],
  onAddBrick,
  onDeleteBrick,
  onUpdateBrick,
  onReorderBricks,
  onCrossContainerDrop,
  documents,
  boards,
  users,
}: UnifiedFormBrickProps) {
  const t = useTranslations("document-detail");
  const { accessToken, activeTeamId } = useSession();
  const params = useParams();
  const currentDocId = (params?.docId || params?.id) as string;
  const currentMeshId = params?.meshId as string;

  const safePages = useMemo(() => {
    const pages = Array.isArray(content.pages)
      ? content.pages
          .filter((page): page is FormPage => Boolean(page && typeof page.id === "string" && page.id.length > 0))
          .map((page, index) => ({
            id: page.id,
            label: typeof page.label === "string" && page.label.trim().length > 0 ? page.label : `Paso ${index + 1}`,
          }))
      : [];

    if (pages.length > 0) return pages;
    return [{ id: DEFAULT_PAGE_ID, label: DEFAULT_PAGE_LABEL }];
  }, [content.pages]);

  const [activePage, setActivePage] = useState(safePages[0]?.id || DEFAULT_PAGE_ID);
  const [values, setValues] = useState<Record<string, string | boolean>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitState, setSubmitState] = useState<"idle" | "success" | "error">("idle");
  const [teamScripts, setTeamScripts] = useState<ScriptSummary[]>([]);
  const [isLoadingScripts, setIsLoadingScripts] = useState(false);
  const [scriptsLoadError, setScriptsLoadError] = useState<string | null>(null);
  const [showTablePicker, setShowTablePicker] = useState(false);
  const [endpointType, setEndpointType] = useState<"webhook" | "database">(content.tableConnectorId ? "database" : "webhook");
  const [localBoards, setLocalBoards] = useState<any[]>(boards || []);
  const [isPrefetchingBoards, setIsPrefetchingBoards] = useState(false);

  useEffect(() => {
    setLocalBoards(boards || []);
  }, [boards]);

  const prefetchBoards = async () => {
    if (!activeTeamId || !accessToken || isPrefetchingBoards) return;
    setIsPrefetchingBoards(true);
    try {
      const freshBoards = await listTeamBoards(activeTeamId, accessToken);
      setLocalBoards(freshBoards);
    } catch (e) {
      console.error("Failed to prefetch boards:", e);
    } finally {
      setIsPrefetchingBoards(false);
    }
  };

  const childrenByContainer = useMemo(() => {
    const raw = content.childrenByContainer;
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {} as Record<string, string[]>;
    return raw as Record<string, string[]>;
  }, [content.childrenByContainer]);

  const pageBricksById = useMemo(() => {
    const map: Record<string, any[]> = {};
    for (const page of safePages) {
      map[page.id] = resolveNestedBricks({ childrenByContainer }, page.id, activeBricks as any[]) as any[];
    }
    return map;
  }, [safePages, childrenByContainer, activeBricks]);

  const pseudoFieldEntries = useMemo(() => {
    const entries: Array<{ brickId: string; pageId: string; config: ReturnType<typeof createDefaultFormFieldConfig> }> = [];
    for (const page of safePages) {
      const pageBricks = pageBricksById[page.id] || [];
      for (const brick of pageBricks) {
        const config = normalizeFormFieldConfig(brick?.content?.formField);
        if (!config) continue;
        entries.push({ brickId: brick.id, pageId: page.id, config });
      }
    }
    return entries;
  }, [safePages, pageBricksById]);

  const fieldIdToBrickId = useMemo(() => {
    const mapping: Record<string, string> = {};
    for (const entry of pseudoFieldEntries) {
      const fieldId = entry.config.fieldId;
      if (!fieldId || mapping[fieldId]) continue;
      mapping[fieldId] = entry.brickId;
    }
    return mapping;
  }, [pseudoFieldEntries]);

  const visiblePseudoFieldEntries = useMemo(() => {
    return pseudoFieldEntries.filter((entry) => {
      const condition = entry.config.condition;
      if (!condition?.enabled) return true;

      const sourceBrickId = fieldIdToBrickId[condition.sourceFieldId];
      const sourceValue = sourceBrickId ? values[sourceBrickId] : undefined;
      return evaluateFieldCondition(condition, sourceValue);
    });
  }, [pseudoFieldEntries, fieldIdToBrickId, values]);

  const visiblePseudoFieldIds = useMemo(() => {
    return new Set(visiblePseudoFieldEntries.map((entry) => entry.brickId));
  }, [visiblePseudoFieldEntries]);

  const hasPseudoFields = pseudoFieldEntries.length > 0;

  const viewerPageBricksById = useMemo(() => {
    const map: Record<string, any[]> = {};
    for (const page of safePages) {
      const pageBricks = pageBricksById[page.id] || [];
      map[page.id] = pageBricks.filter((brick) => {
        const config = normalizeFormFieldConfig(brick?.content?.formField);
        if (!config) return true;
        return visiblePseudoFieldIds.has(brick.id);
      });
    }
    return map;
  }, [safePages, pageBricksById, visiblePseudoFieldIds]);

  const navigablePages = useMemo(() => {
    if (canEdit || !hasPseudoFields) return safePages;
    const filtered = safePages.filter((page) => {
      const bricks = viewerPageBricksById[page.id] || [];
      return bricks.length > 0;
    });
    return filtered.length > 0 ? filtered : [safePages[0]];
  }, [canEdit, hasPseudoFields, safePages, viewerPageBricksById]);

  const activePageBricks = (canEdit ? pageBricksById[activePage] : viewerPageBricksById[activePage]) || [];

  const webhookBase = useMemo(
    () =>
      (
        process.env.NEXT_PUBLIC_API_BASE_URL ??
        process.env.NEXT_PUBLIC_KILLIO_API_URL ??
        process.env.NEXT_PUBLIC_API_URL ??
        "http://localhost:4000"
      ).replace(/\/+$/, ""),
    [],
  );

  const webhookScripts = useMemo(() => {
    return teamScripts.filter((script) => {
      const publicToken = script.triggerConfig?.publicToken;
      return script.triggerType === "webhook" && script.isActive && typeof publicToken === "string" && publicToken.length > 0;
    });
  }, [teamScripts]);

  const endpoint = String(content.webhookUrl ?? "").trim();
  const submitLabel = (content.submitLabel || t("form.submitButton") || "Enviar").trim();
  const successMessage = (content.successMessage || t("form.successMessage") || "Enviado correctamente.").trim();

  const isConfigured = endpoint.length > 0 && hasPseudoFields;

  useEffect(() => {
    if (navigablePages.some((page) => page.id === activePage)) return;
    setActivePage(navigablePages[0]?.id || DEFAULT_PAGE_ID);
  }, [navigablePages, activePage]);

  const updateContent = (patch: Partial<FormBrickContent>) => {
    onUpdate({ ...content, ...patch });
  };

  const updatePages = (nextPages: FormPage[]) => {
    const nextChildrenByContainer: Record<string, string[]> = {};
    for (const page of nextPages) {
      nextChildrenByContainer[page.id] = Array.isArray(childrenByContainer[page.id]) ? childrenByContainer[page.id] : [];
    }

    updateContent({
      pages: nextPages,
      childrenByContainer: nextChildrenByContainer,
    });
  };

  const addPage = () => {
    const nextPage = createPage(safePages.length + 1);
    const nextPages = [...safePages, nextPage];
    updatePages(nextPages);
    setActivePage(nextPage.id);
  };

  const removePage = (pageId: string) => {
    if (safePages.length <= 1) return;
    const nextPages = safePages.filter((page) => page.id !== pageId);
    updatePages(nextPages);
    if (activePage === pageId) {
      setActivePage(nextPages[0].id);
    }
  };

  const renamePage = (pageId: string, label: string) => {
    updatePages(safePages.map((page) => (page.id === pageId ? { ...page, label } : page)));
  };

  const addFieldBrick = () => {
    if (!canEdit || !onAddBrick) return;

    const afterBrickId = activePageBricks.length > 0 ? activePageBricks[activePageBricks.length - 1].id : undefined;
    onAddBrick(
      "text",
      afterBrickId,
      { parentId: id, containerId: activePage },
      {
        text: "",
        markdown: "",
        displayStyle: "paragraph",
        formField: createDefaultFormFieldConfig(),
      },
    );
  };

  const reorderActivePageBricks = (orderedIds: string[]) => {
    if (!canEdit) return;
    const nextChildrenByContainer = {
      ...childrenByContainer,
      [activePage]: orderedIds,
    };
    updateContent({ childrenByContainer: nextChildrenByContainer });
  };

  const getWebhookUrlForScript = (script: ScriptSummary): string | null => {
    const publicToken = script.triggerConfig?.publicToken;
    if (!activeTeamId || typeof publicToken !== "string" || publicToken.length === 0) {
      return null;
    }
    return `${webhookBase}/w/${activeTeamId}/webhook/${script.id}/${publicToken}`;
  };

  const refreshScripts = async () => {
    if (!activeTeamId || !accessToken) return;
    setIsLoadingScripts(true);
    setScriptsLoadError(null);
    try {
      const scripts = await listScripts(activeTeamId, accessToken);
      setTeamScripts(scripts);
    } catch (error) {
      console.error("Failed to load webhook scripts for form brick", error);
      setScriptsLoadError("No se pudieron cargar los scripts.");
    } finally {
      setIsLoadingScripts(false);
    }
  };

  const handleScriptSelection = (scriptId: string) => {
    if (!scriptId) {
      updateContent({ scriptId: undefined });
      return;
    }

    const script = webhookScripts.find((item) => item.id === scriptId);
    if (!script) {
      toast("Script no valido para webhook.", "error");
      return;
    }

    const webhookUrl = getWebhookUrlForScript(script);
    if (!webhookUrl) {
      toast("No se pudo construir la URL del webhook.", "error");
      return;
    }

    updateContent({
      scriptId: script.id,
      webhookUrl,
      tableConnectorId: undefined,
      tableConnectorSource: undefined,
      tableConnectorDocId: undefined,
      tableConnectorLabel: undefined,
      autoGeneratedFields: undefined,
    });
  };

  const handleTableSelection = async (selection: TableBrickPickerSelection) => {
    setShowTablePicker(false);
    
    if (!activeTeamId || !accessToken) {
      toast("No se puede conectar a la base de datos sin estar autenticado.", "error");
      return;
    }

    // Auto-generate form fields from the target structure
    let newFields: any[] = [];
    if (selection.source === "board") {
      // Kanban intake form: title + description + dueAt + tags (if the board has any)
      newFields = generateCardFormFields(selection.boardTags);
    } else if (selection.brickContent?.columns && Array.isArray(selection.brickContent.columns)) {
      newFields = generateFormFieldsFromColumns(selection.brickContent.columns);
    }

    // Map selection to the generic backend sourceType/sourceId/brickId contract:
    //   document  → sourceType='document', sourceId=docId,   brickId=brickId
    //   mesh      → sourceType='mesh',     sourceId=meshId,  brickId=brickId
    //   board     → sourceType='board',    sourceId=boardId, brickId=listId
    let sourceType: string;
    let sourceId: string | undefined;
    let brickId: string;

    if (selection.source === "board") {
      sourceType = "board";
      sourceId = selection.boardId;
      brickId = selection.listId!; // listId stored in brickId and listId fields
    } else if (selection.source === "mesh") {
      sourceType = "mesh";
      sourceId = selection.meshId;
      brickId = selection.brickId;
    } else {
      // "local" or "document"
      sourceType = "document";
      sourceId = selection.source === "local" ? currentDocId : selection.documentId;
      brickId = selection.brickId;
    }

    if (!sourceId) {
      toast("No se pudo determinar el origen de la tabla.", "error");
      return;
    }

    try {
      const response = await fetch(`${webhookBase}/w/${activeTeamId}/brick/token`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify({
          brickId,
          sourceType,
          sourceId,
          permission: 2, // write-only
        }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error((err as any).message || "Failed to generate token");
      }

      const { token } = await response.json();
      const dbUrl = `${webhookBase}/public/brick/${token}`;

      updateContent({
        tableConnectorId: brickId,
        tableConnectorSource: selection.source,
        tableConnectorDocId: selection.documentId,
        tableConnectorLabel: selection.label,
        fields: undefined,
        autoGeneratedFields: true,
        scriptId: undefined,
        webhookUrl: dbUrl,
      });

      if (onAddBrick) {
        if (onDeleteBrick && pseudoFieldEntries.length > 0) {
          for (const entry of pseudoFieldEntries) {
            onDeleteBrick(entry.brickId);
          }
        }
        for (const field of newFields) {
          onAddBrick("text", undefined, { parentId: id, containerId: safePages[0].id }, {
            markdown: "",
            displayStyle: "paragraph",
            formField: {
              fieldId: field.id,
              type: field.type,
              label: field.label,
              required: field.required,
              placeholder: field.placeholder,
              options: field.options,
              condition: { enabled: false },
            }
          });
        }
      }
    } catch (error) {
      console.error("Error creating database token", error);
      toast(`Error conectando: ${(error as Error).message}`, "error");
    }
  };

  useEffect(() => {
    if (!canEdit || !activeTeamId || !accessToken) return;

    let cancelled = false;
    const loadScripts = async () => {
      setIsLoadingScripts(true);
      setScriptsLoadError(null);
      try {
        const scripts = await listScripts(activeTeamId, accessToken);
        if (cancelled) return;
        setTeamScripts(scripts);
      } catch (error) {
        if (cancelled) return;
        console.error("Failed to load webhook scripts for form brick", error);
        setScriptsLoadError("No se pudieron cargar los scripts.");
      } finally {
        if (!cancelled) setIsLoadingScripts(false);
      }
    };

    loadScripts();
    return () => {
      cancelled = true;
    };
  }, [canEdit, activeTeamId, accessToken]);

  useEffect(() => {
    if (!canEdit || !content.scriptId) return;
    const selectedScript = webhookScripts.find((script) => script.id === content.scriptId);
    if (!selectedScript) return;

    const webhookUrl = getWebhookUrlForScript(selectedScript);
    if (!webhookUrl) return;

    if (webhookUrl !== (content.webhookUrl ?? "")) {
      updateContent({ scriptId: selectedScript.id, webhookUrl });
    }
  }, [canEdit, content.scriptId, content.webhookUrl, webhookScripts]);

  const setFieldValue = (brickId: string, value: string | boolean) => {
    setValues((current) => ({ ...current, [brickId]: value }));
  };

  const activePageIndex = navigablePages.findIndex((page) => page.id === activePage);
  const isLastPage = activePageIndex >= navigablePages.length - 1;

  const goToNextPage = () => {
    if (activePageIndex < 0 || isLastPage) return;

    const currentRequiredMissing = visiblePseudoFieldEntries.find((entry) => {
      return entry.pageId === activePage && isRequiredFieldMissing(entry.config.type, entry.config.required, values[entry.brickId]);
    });

    if (currentRequiredMissing) {
      toast("Completa los campos obligatorios de este paso.", "error");
      return;
    }

    setActivePage(navigablePages[activePageIndex + 1].id);
  };

  const goToPreviousPage = () => {
    if (activePageIndex <= 0) return;
    setActivePage(safePages[activePageIndex - 1].id);
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();

    if (hasPseudoFields && !isLastPage) {
      goToNextPage();
      return;
    }

    if (!isConfigured) {
      toast(t("form.missingEndpoint") || "Configura la URL del webhook antes de enviar.", "error");
      return;
    }

    if (hasPseudoFields) {
      const missingEntry = visiblePseudoFieldEntries.find((entry) => {
        return isRequiredFieldMissing(entry.config.type, entry.config.required, values[entry.brickId]);
      });

      if (missingEntry) {
        setActivePage(missingEntry.pageId);
        toast("Completa los campos obligatorios antes de enviar.", "error");
        return;
      }
    }

    setIsSubmitting(true);
    setSubmitState("idle");
    try {
      const normalizedValues = visiblePseudoFieldEntries.reduce<Record<string, string | boolean>>((acc, entry) => {
        const value = values[entry.brickId];
        if (typeof value === "undefined") return acc;
        const key = entry.config.fieldId || entry.brickId;
        acc[key] = value;
        return acc;
      }, {});

      const payload = {
        formId: id,
        title: content.title || "",
        scriptId: content.scriptId || null,
        submittedAt: new Date().toISOString(),
        values: normalizedValues,
        fields: visiblePseudoFieldEntries.map((entry) => ({
          brickId: entry.brickId,
          pageId: entry.pageId,
          ...entry.config,
        })),
      };

      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error("Webhook rejected the submission.");
      }

      setSubmitState("success");
      toast(successMessage, "success");
      setValues({});
      setActivePage(navigablePages[0]?.id || DEFAULT_PAGE_ID);
      setTimeout(() => setSubmitState("idle"), 8000);
    } catch (error) {
      console.error("Failed to submit form brick", error);
      setSubmitState("error");
      toast(t("form.submitError") || "No se pudo enviar el formulario.", "error");
    } finally {
      setIsSubmitting(false);
    }
  };

  const previewLabel = useMemo(() => {
    return content.title || t("form.defaultTitle") || "Formulario";
  }, [content.title, t]);

  if (canEdit) {
    return (
      <div className="rounded-xl border border-border bg-card p-4 shadow-sm space-y-4">
        <div className="space-y-2">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">{t("form.editorTitle") || "Formulario"}</p>
              <p className="text-sm font-medium text-foreground">{previewLabel}</p>
            </div>
            <div className="flex bg-muted/40 p-0.5 rounded-md border border-border/50">
              <button
                type="button"
                onClick={() => setEndpointType("webhook")}
                className={`px-2 py-1 text-[10px] font-semibold uppercase tracking-wider rounded-sm transition-colors ${
                  endpointType === "webhook" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
                }`}
              >
                Webhook
              </button>
              <button
                type="button"
                onClick={() => setEndpointType("database")}
                className={`px-2 py-1 text-[10px] font-semibold uppercase tracking-wider rounded-sm transition-colors ${
                  endpointType === "database" ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
                }`}
              >
                Objeto
              </button>
            </div>
          </div>

          <Input
            value={content.title || ""}
            onChange={(event) => updateContent({ title: event.target.value })}
            placeholder={t("form.titlePlaceholder") || "Titulo del formulario"}
          />
          <Input
            value={content.description || ""}
            onChange={(event) => updateContent({ description: event.target.value })}
            placeholder={t("form.descriptionPlaceholder") || "Descripcion opcional"}
          />

          {endpointType === "webhook" ? (
            <>
              <div className="rounded-md border border-border/60 bg-muted/20 p-3 space-y-2">
                <div className="flex items-center justify-between gap-2">
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Conectar script</p>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="h-7 px-2 text-xs"
                    onClick={refreshScripts}
                    disabled={isLoadingScripts || !activeTeamId || !accessToken}
                  >
                    {isLoadingScripts ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : "Refrescar"}
                  </Button>
                </div>

                <select
                  value={content.scriptId || ""}
                  onChange={(event) => handleScriptSelection(event.target.value)}
                  className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none"
                  disabled={!activeTeamId || !accessToken || isLoadingScripts}
                >
                  <option value="">Ninguno (usar URL manual)</option>
                  {webhookScripts.map((script) => (
                    <option key={script.id} value={script.id}>
                      {script.name}
                    </option>
                  ))}
                </select>

                {scriptsLoadError ? <p className="text-xs text-destructive">{scriptsLoadError}</p> : null}
                {!isLoadingScripts && webhookScripts.length === 0 ? (
                  <p className="text-xs text-muted-foreground">No hay scripts webhook activos en este workspace.</p>
                ) : null}
                {content.scriptId ? (
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs text-muted-foreground">Webhook conectado automaticamente desde el script seleccionado.</p>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-xs"
                      onClick={() => updateContent({ scriptId: undefined })}
                    >
                      Desconectar
                    </Button>
                  </div>
                ) : null}
              </div>

              <Input
                value={content.webhookUrl || ""}
                onChange={(event) => updateContent({ webhookUrl: event.target.value, scriptId: undefined, tableConnectorId: undefined })}
                placeholder={t("form.webhookPlaceholder") || "URL del webhook publico"}
                disabled={!!content.scriptId}
              />
            </>
          ) : (
            <div className="rounded-md border border-border/60 bg-muted/20 p-4 space-y-3">
              <div className="flex items-center justify-between gap-2">
                <p className="text-sm font-semibold text-foreground">Conectar a Objeto</p>
                <Button type="button" variant="outline" size="sm" onClick={() => setShowTablePicker(true)} onMouseEnter={prefetchBoards}>
                  Seleccionar Objeto
                </Button>
              </div>
              
              {content.tableConnectorId ? (
                <div className="rounded border border-primary/20 bg-primary/5 p-3 space-y-2">
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-medium text-primary">{content.tableConnectorLabel || "Tabla seleccionada"}</p>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="h-6 px-2 text-xs text-destructive hover:text-destructive hover:bg-destructive/10"
                      onClick={() => updateContent({ tableConnectorId: undefined, tableConnectorLabel: undefined, webhookUrl: undefined })}
                    >
                      Desconectar
                    </Button>
                  </div>
                  {content.autoGeneratedFields && (
                    <p className="text-xs text-muted-foreground">Las preguntas del formulario se han generado automáticamente usando las columnas de la tabla.</p>
                  )}
                  <p className="text-[10px] text-muted-foreground break-all">{content.webhookUrl}</p>
                </div>
              ) : (
                <p className="text-sm text-muted-foreground text-center py-2">
                  Selecciona una tabla, mesh o lista Kanban para conectar este formulario. Las respuestas se guardarán como filas (tabla) o cards (Kanban).
                </p>
              )}
            </div>
          )}

          <div className="grid grid-cols-2 gap-2">
            <Input
              value={content.submitLabel || ""}
              onChange={(event) => updateContent({ submitLabel: event.target.value })}
              placeholder={t("form.submitLabelPlaceholder") || "Etiqueta del boton"}
            />
            <Input
              value={content.successMessage || ""}
              onChange={(event) => updateContent({ successMessage: event.target.value })}
              placeholder={t("form.successPlaceholder") || "Mensaje al enviar"}
            />
          </div>
        </div>

        <div className="rounded-lg border border-border/60">
          <div className="flex bg-muted/20 border-b border-border/50 px-1 pt-1 overflow-x-auto overflow-y-hidden">
            {safePages.map((page) => (
              <div
                key={page.id}
                className={`group/tab flex items-center px-4 py-2 border-b-2 text-sm font-medium transition-colors cursor-pointer whitespace-nowrap ${
                  activePage === page.id
                    ? "border-primary text-foreground bg-background"
                    : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/10"
                }`}
                onClick={() => setActivePage(page.id)}
              >
                <input
                  value={page.label}
                  onChange={(event) => renamePage(page.id, event.target.value)}
                  className="bg-transparent outline-none border-none min-w-[70px] focus:ring-1 ring-border/50 rounded px-1"
                  onClick={(event) => {
                    event.stopPropagation();
                  }}
                />
                {safePages.length > 1 && (
                  <button
                    type="button"
                    className="ml-2 opacity-0 group-hover/tab:opacity-100 hover:text-destructive transition-opacity"
                    onClick={(event) => {
                      event.stopPropagation();
                      removePage(page.id);
                    }}
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            ))}

            <button
              type="button"
              onClick={addPage}
              className="px-3 py-2 text-muted-foreground hover:text-foreground flex items-center justify-center transition-colors"
            >
              <Plus className="w-4 h-4" />
            </button>
          </div>

          <div className="p-3 space-y-3 bg-background">
            <div className="flex items-center justify-between gap-2">
              <p className="text-sm font-semibold text-foreground">{safePages.find((page) => page.id === activePage)?.label || "Paso"}</p>
              <Button type="button" variant="outline" size="sm" onClick={addFieldBrick} className="h-8 gap-2">
                <Plus className="h-3.5 w-3.5" />
                Field brick
              </Button>
            </div>

            <UnifiedBrickList
              hasExternalDndContext={true}
              showDragOverlay={false}
              dropContainerToken={`${id}:${activePage}`}
              bricks={activePageBricks}
              activeBricks={activeBricks}
              canEdit={canEdit}
              emptyPlaceholder="Paso vacio. Agrega un field brick o cualquier bloque."
              onUpdateBrick={(brickId, nextContent) => onUpdateBrick?.(brickId, nextContent)}
              onDeleteBrick={(brickId) => onDeleteBrick?.(brickId)}
              onReorderBricks={reorderActivePageBricks}
              onAddBrick={(kind, afterBrickId, parentProps, initialContent) =>
                onAddBrick?.(kind, afterBrickId, parentProps || { parentId: id, containerId: activePage }, initialContent)
              }
              onCrossContainerDrop={onCrossContainerDrop}
              documents={documents}
              boards={boards}
              users={users}
              addableKinds={[
                "text",
                "table",
                "database",
                "graph",
                "form",
                "checklist",
                "accordion",
                "tabs",
                "columns",
                "image",
                "video",
                "audio",
                "file",
                "code",
                "bookmark",
                "math",
              ]}
            />
          </div>
        </div>

        {showTablePicker && (
          <TableBrickPicker
            onSelect={handleTableSelection}
            onClose={() => setShowTablePicker(false)}
            documents={documents || []}
            boards={localBoards}
            activeBricks={activeBricks || []}
          />
        )}
      </div>
    );
  }

  if (!isConfigured) {
    return (
      <div className="rounded-xl border border-dashed border-border bg-muted/20 p-6 text-center text-sm text-muted-foreground">
        {t("form.notConfigured") || "Este formulario todavia no esta configurado."}
      </div>
    );
  }


  return (
    <div className="rounded-xl border border-border bg-card p-5 shadow-sm space-y-5">
      <div className="space-y-1.5">
        <p className="text-xs font-semibold uppercase tracking-widest text-accent">{t("form.viewerTitle") || "Formulario"}</p>
        <h3 className="text-xl font-semibold tracking-tight text-foreground">{content.title || t("form.defaultTitle") || "Formulario"}</h3>
        {content.description ? <p className="text-sm text-muted-foreground">{content.description}</p> : null}
      </div>

      <FormFieldRuntimeProvider
        value={{
          interactive: true,
          values,
          setValue: setFieldValue,
        }}
      >
        <form className="space-y-4" onSubmit={handleSubmit}>
          {navigablePages.length > 1 && (
            <div className="flex flex-wrap gap-2">
              {navigablePages.map((page, index) => (
                <button
                  key={page.id}
                  type="button"
                  onClick={() => setActivePage(page.id)}
                  className={`rounded-md px-3 py-1.5 text-xs font-semibold transition-colors ${
                    activePage === page.id
                      ? "bg-accent text-accent-foreground"
                      : "bg-muted/40 text-muted-foreground hover:bg-muted"
                  }`}
                >
                  {index + 1}. {page.label}
                </button>
              ))}
            </div>
          )}

          <div className="rounded-lg border border-border/60 bg-background p-3">
            <UnifiedBrickList
              hasExternalDndContext={true}
              dropContainerToken={`${id}:${activePage}`}
              bricks={activePageBricks}
              activeBricks={activeBricks}
              canEdit={false}
              emptyPlaceholder="Paso sin contenido"
              onUpdateBrick={() => undefined}
              onDeleteBrick={() => undefined}
              onReorderBricks={() => undefined}
              onAddBrick={() => undefined}
              documents={documents}
              boards={boards}
              users={users}
            />
          </div>

          {navigablePages.length > 1 ? (
            <div className="flex items-center justify-between gap-2 pt-1">
              <Button type="button" variant="outline" onClick={goToPreviousPage} disabled={activePageIndex <= 0} className="gap-2">
                <ChevronLeft className="h-4 w-4" />
                Anterior
              </Button>
              {!isLastPage ? (
                <Button type="button" onClick={goToNextPage} className="gap-2">
                  Siguiente
                  <ChevronRight className="h-4 w-4" />
                </Button>
              ) : (
                <Button type="submit" className="gap-2" disabled={isSubmitting}>
                  {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                  {submitLabel}
                </Button>
              )}
            </div>
          ) : (
            <div className="flex justify-end pt-1">
              <Button type="submit" className="gap-2" disabled={isSubmitting}>
                {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                {submitLabel}
              </Button>
            </div>
          )}
        </form>
      </FormFieldRuntimeProvider>

      {submitState === "success" ? (
        <div className="rounded-md bg-emerald-50 dark:bg-emerald-500/10 p-4 border border-emerald-200 dark:border-emerald-500/20 flex items-center justify-between gap-3">
          <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">{successMessage}</p>
          <button
            type="button"
            onClick={() => setSubmitState("idle")}
            className="text-xs font-medium text-emerald-600 dark:text-emerald-400 underline underline-offset-2 hover:no-underline whitespace-nowrap shrink-0"
          >
            Enviar otra
          </button>
        </div>
      ) : null}
      {submitState === "error" ? (
        <div className="rounded-md bg-destructive/10 p-3 border border-destructive/20">
          <p className="text-sm font-medium text-destructive">{t("form.submitError") || "No se pudo enviar el formulario."}</p>
        </div>
      ) : null}
    </div>
  );
}
